"""init clean schema

Revision ID: d986f2a8ed5d
Revises: 
Create Date: 2025-09-16 20:10:41.343730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd986f2a8ed5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('integration_target', sa.String(), nullable=True),
    sa.Column('disintegration_target', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_dimension_id'), 'dimension', ['id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scoring_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_version_id'), 'test_version', ['id'], unique=False)
    op.create_table('facet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facet_id'), 'facet', ['id'], unique=False)
    op.create_table('score_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('raw_sum', sa.JSON(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('main_type', sa.String(), nullable=True),
    sa.Column('wing_distribution', sa.JSON(), nullable=True),
    sa.Column('health', sa.JSON(), nullable=True),
    sa.Column('integration', sa.JSON(), nullable=True),
    sa.Column('disintegration', sa.JSON(), nullable=True),
    sa.Column('center_scores', sa.JSON(), nullable=True),
    sa.Column('subtypes', sa.JSON(), nullable=True),
    sa.Column('validity', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_score_profile_id'), 'score_profile', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_version_id', sa.Integer(), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('reverse_scored', sa.Boolean(), nullable=True),
    sa.Column('response_scale', sa.String(), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('facet_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.ForeignKeyConstraint(['facet_id'], ['facet.id'], ),
    sa.ForeignKeyConstraint(['test_version_id'], ['test_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_table('item_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('weight', sa.JSON(), nullable=True),
    sa.Column('a', sa.JSON(), nullable=True),
    sa.Column('b', sa.JSON(), nullable=True),
    sa.Column('c', sa.Integer(), nullable=True),
    sa.Column('last_calibrated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_param_id'), 'item_param', ['id'], unique=False)
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('raw_choice', sa.Integer(), nullable=False),
    sa.Column('scored_value', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_id'), 'response', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_id'), table_name='response')
    op.drop_table('response')
    op.drop_index(op.f('ix_item_param_id'), table_name='item_param')
    op.drop_table('item_param')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_score_profile_id'), table_name='score_profile')
    op.drop_table('score_profile')
    op.drop_index(op.f('ix_facet_id'), table_name='facet')
    op.drop_table('facet')
    op.drop_index(op.f('ix_test_version_id'), table_name='test_version')
    op.drop_table('test_version')
    op.drop_table('session')
    op.drop_index(op.f('ix_dimension_id'), table_name='dimension')
    op.drop_table('dimension')
    # ### end Alembic commands ###
